### ISSUE TITLE
Boxplot enhancments

### ISSUE THREAD

**Issue by ldecicco-USGS** [USGS-R/smwrGraphs#24]
From an email:
1. Can you extend the range of the y-axes on the boxplots to ensure that the sample count is always above the highest far-out value?  (note: I think I've only seen this on the log-axis plots).
2. Can you add commas to any count over 999 in the boxplot sample counts?

I think both are USGS style requirements.  Here's an example:

```
x <- c(rnorm(100000, 150, 270),9070)
x[x<=0] <- 10
groups <- c(rep("A",50000),rep("B",50001))

setPDF("test",layout="portrait")
boxPlot(x, group=groups, 
        Box=list(type="tukey"),
        yaxis.log=TRUE)
graphics.off()
```

**Comment by dlorenz-usgs** [comment]
The answer to the first one is easy--the y-axis limits can be set using the
yaxis.range argument, just as you would do that in any other of the
functions in smwrGraphs. See below, note that because there are more than 3
log cycles, you need to specify full cycles.

boxPlot(x, group=groups,
        Box=list(type="tukey"),
        yaxis.log=TRUE, yaxis.range=10^c(-2,5))

The answer to the second one would require a modification to the code. That
issue has not come up in the past several years as it is very unusual to
have that many observations and typically another type of graph would be
used for that many points and not a box plot. None the less, the format
should include a comma and that will be added.

**Comment by ldecicco-USGS** [comment]
For #1, I was working on a way to programmatically check to see if the text shows up in the same y-range as the data. If it does, add another 'pretty' tick (via extending the yaxis.range). If you don't think that's worth adding to the package, I'll just leave it in an external script. 95% of the time, this isn't a problem, but of course, the ones that have the problem stick out.

**Comment by dlorenz-usgs** [comment]
Well, there should be code to do that--in renderBoxPlot, lines 71-75 should
do the automatic extension. I see that there is an error in the code. Lines
71-75 are

if(Box$show.counts)
if(yaxis.log)
yrange <- yrange + c(0, 0.0414) * diff(yrange)
else
yrange <- yrange * c(1, 1.10)

but should be

  if(Box$show.counts) if(yaxis.log) { yrange <- yrange * c(1, 10^(0.0414 *
diff(log10(yrange)))) } else { yrange <- yrange * c(1, 1.10) } }

Line 151 was changed to use prettyNum instead of as.character

Changes were committed (or will be as soon as this is sent).

**Comment by ldecicco-USGS** [comment]
Excellent! Thanks!

**Comment by ldecicco-USGS** [comment]
Do you mind if I tag this release and send it to GRAN?

**Comment by dlorenz-usgs** [comment]
I do not mind, please do.
