### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by tmills-usgs** [USGS-R/smwrGraphs#7]
When trying to install the package using the installation instructions in the readme I get the following error:

> install.packages("smwrGraphs", 
+                  repos=c("http://owi.usgs.gov/R",
+                          "http://cran.us.r-project.org"), 
+                  dependencies = TRUE)
Warning in install.packages :
  cannot open: HTTP status was '404 Not Found'
Warning in install.packages :
  cannot open: HTTP status was '404 Not Found'
Warning in install.packages :
  unable to access index for repository http://owi.usgs.gov/R/bin/windows/contrib/3.0

   package ‘smwrGraphs’ is available as a source package but not as a binary

Warning in install.packages :
  package ‘smwrGraphs’ is not available (for R version 3.0.2)

**Comment by ldecicco-USGS** [comment]
We are calling the owi repo 'GRAN' (Geological R Archive Network'. Going forward, it will have binaries for the current R release and the previous release (so, when R 3.2 comes out, we'll support 3.2 and 3.1 binaries). Currently, we are only supporting R 3.1 (since this is still in it's infancy). So...you an either update your R, or install from source:

```r
install.packages("smwrGraphs", 
    repos=c("http://owi.usgs.gov/R", "http://cran.us.r-project.org"), 
    type="source",
    dependencies = TRUE)
```

Side note, I'll be updating GRAN today (3/30/15), that will include an updated version of smwrGraphs, so if you wait until this afternoon, you'll get the most up-to-date version.

**Comment by tmills-usgs** [comment]
Excellent, thank you
